#!/usr/bin/env python3

import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtWebKit import *
from PyQt5.QtWebKitWidgets import *
from PyQt5.QtWidgets import QApplication, QWidget, QMainWindow

host='localhost'
port='8000'

for arg in sys.argv:
    if arg.find('host=') == 0:
        host=arg.replace('host=','')
    if arg.find('port=') == 0:
        port=arg.replace('port=','')

app = QApplication(sys.argv)
web = QWebView()

host='http://'+host
print('loading '+host+':'+port)

web.resize(1000,600)
web.load(QUrl(host+':'+port))
web.show()

sys.exit(app.exec_())
